{
    'name': 'Sports Association',
    'summary': 'Manage sports association, teams and events.',
    'version': '17.0.1.0.0',
    'category': 'Sports',
    'author': 'Yuniel Villalón',
    'license': 'AGPL-3',
    'application': False,
    'installable': True,
    'depends': ['base','web'],
    'data': [
            'wizards/sport_create_match.xml',
            'data/ir_cron.xml',
            'data/sport_licence_data.xml',
            'data/sport_tag_data.xml',
            'security/groups.xml',
            'security/ir.model.access.csv',
            'views/sport_issue_views.xml',
            'views/sport_clinic_views.xml',
            'views/sport_issue_tag_views.xml',
            'views/sport_sport_views.xml',
            'views/sport_team_views.xml',
            'views/sport_player_views.xml',
            'views/sport_league_views.xml',
            'views/sport_match_views.xml',
            'views/sport_menuitems.xml',
            'wizards/sport_create_issue_wizard.xml',
            'wizards/sport_issue_state.xml',

            'report/sport_issue_report.xml',
            'report/sport_league_report.xml',
            'report/sport_match_report.xml',
],
}
